### ISSUE TITLE
Some Question About MGI

### ISSUE THREAD

**Issue by jumptiger66** [YananGu/DVC#2]
It seems that online class-incremental learning is actually different from classical class-incremental learning. Your first step is to choose important old examples from memory bank and mix them with incoming data (new data for this step). Secondly, the model is trained only once with the mixed data. 
So i get some questions about step one. It seems that Memory bank can store much more images ,so that you need to choose part of them to be mixed with incoming data.For example , you can replay 2000 images and store 5000 images as memory bank, so you need to use MGI to select 2000 images from memory bank .However, in classical class-incremental learning , we often set a fixed memory bank and dont need to choose but use all of them.
All my doubts are conceptual ambiguities. If you can tell me some about them ,I would appreciate it.

**Comment by YananGu** [comment]
Yes, you are right.  This is indeed one aspect of the difference between the two incremental learning settings.  In fact,  we set the model receives a batch of size 10 at a time (Imagine an endless stream of data, but the data sent into the model at every moment is actually limited) from the data stream, and the size of the retrieved batch is also set to 10 irrespective of the size of the memory（Retrieving too many samples of old classes will affect the online learning of new classes and increase the burden of online learning）.  All these settings are designed to be closer to the "online" scene，several classic online class incremental learning methods are also set in this way( MIR,ASER).

**Comment by jumptiger66** [comment]
OH，thank u for your reply .

I think i get the setting about  'online' class-incremental learning.
In my opinion, in one step , we have memory bank which contains 2K old images and there are 5K new images. However, we can only train our model for 500 times when we use 10 new images at a time because every new images can be used once. Each time we get 10 new images , we select 10 old images from memory bank to be mixed with these new images. Your MGI is the way to select representative old images. And in this setting , we may make full use of memory bank but some old images may not be used for their weak expressive force.

Best regards !

**Comment by YananGu** [comment]
Yes, this is also the main MGI idea expressed in our paper.
