### ISSUE TITLE
the meaning of num_runs

### ISSUE THREAD

**Issue by zhangziyi1670** [YananGu/DVC#5]
I notice that the value of num_runs is set to 15 and the value of num_tasks is set to 10 in your code for CIFAR100. I wonder the meaning of num_runs. Hope for your replay.

**Comment by YananGu** [comment]
Thanks for your interest in our work. Because of the random sampling process, and other random factors, the results of each experiment can be biased. We run the algorithm for 15 times and take the average value of the results for 15 times to ensure the stability of the performance
